### PR TITLE
Readme update

### PR DESCRIPTION
**Pull request by senhas-rgb**
Proper dependency installation guide for arch linux users.

### CODE REVIEW

**Comment by Nyvyme** [comment]
Users can find these packages in official Arch Linux package repositories and/or AUR repository.
If you really want to add this information, add separate file with build instructions for (almost) every popular Linux distribution.
For now, I'll convert this pull request to "DRAFT".

**Comment by senhas-rgb** [comment]
Well one dependency for arch wasn't listed correctly in the build instructions making it fail on me for multiple times

**Comment by senhas-rgb** [comment]
I should Include that too wait imma add that

**Comment by senhas-rgb** [comment]
OK ready for review this is essential for some users that don't know what the error actually states

**Comment by Nyvyme** [comment]
Sorry, forgot to revert changes for old default make pipeline. GNU xorriso is added to "Tools" section.

**Comment by Nyvyme** [comment]
And as I said previously, if you want to add this information, make a SEPARATE file with build instructions and then I'll add a link to it in `README.md`.

**Comment by senhas-rgb** [comment]
ok

**Review by Nyvyme — COMMENTED** [review]
Not bad, ready for merge.

**Pull request merged**
